[com_users] Poprawa tłumaczenia
JoomlaPolska/jezyk-J4 pull request #221
Opened 2022-08-25 19:08 UTC by Valdnet

Poprawione tłumaczenie dla komponentu użytkownika.

2022-08-25 20:59 UTC, zwiastunsw requested changes
Dzięki. W komentarzach trochę sugestii i info o rzeczach, które nie powinny być zmieniane. (Nie wychwyciłem wszystkich "Wprowadź")

2022-08-25 20:59 UTC, zwiastunsw commented on language/pl-PL/com_users.ini
> +COM_USERS_USER_FIELD_FRONTEND_LANGUAGE_LABEL="Język interfejsu"
Fronton nazywamy witryną. Też od lat.  Zatem: Język witryny
```suggestion
COM_USERS_USER_FIELD_FRONTEND_LANGUAGE_LABEL="Język witryny"
```

2022-08-25 20:59 UTC, zwiastunsw commented on language/pl-PL/com_users.ini
> +COM_USERS_RESET_REQUEST_LABEL="Wprowadź adres e-mail swojego konta. Kod weryfikacyjny zostanie wysłany do Ciebie. Po otrzymaniu kodu weryfikacyjnego będziesz mógł wybrać nowe hasło do swojego konta."
Rozważaliśmy to przed kilku laty i zdecydowaliśmy się na krótsze Wpisz, ale nie upieram się.
```suggestion
COM_USERS_RESET_REQUEST_LABEL="Wpisz adres e-mail swojego konta. Kod weryfikacyjny zostanie wysłany do Ciebie. Po otrzymaniu kodu weryfikacyjnego będziesz mógł wybrać nowe hasło do swojego konta."
```

2022-08-25 20:59 UTC, zwiastunsw commented on language/pl-PL/com_users.ini
> +COM_USERS_REGISTRATION_VERIFY_SUCCESS="Twój adres e-mail został zweryfikowany. Kiedy administrator zatwierdzi Twoje konto, otrzymasz powiadomienie e-mailem, po którym będziesz mółg zalogować się na s
Gdzie to możliwe, szukamy formy "bezpłciowej". Niekoniecznie też trzeba dopisywać przymiotnik "internetowej" do strony - to oczywiste. Może więc tak 
```suggestion
COM_USERS_REGISTRATION_VERIFY_SUCCESS="Twój adres e-mail został zweryfikowany. Kiedy administrator zatwierdzi Twoje konto, otrzymasz powiadomienie e-mailem, po którym możesz się zalogować do witryny."
```

2022-08-25 20:59 UTC, zwiastunsw commented on language/pl-PL/com_users.ini
> +COM_USERS_REGISTRATION_SEND_MAIL_FAILED="Wystąpił błąd podczas wysyłania wiadomości e-mail w czasie rejestracji użytkownika. Wiadomość została wysłana do administratora tej strony internetowej."
Skoro już poprawiamy, to "stronę internetową" zamieniałbym konsekwentnie na "witrynę"
```suggestion
COM_USERS_REGISTRATION_SEND_MAIL_FAILED="Wystąpił błąd podczas wysyłania wiadomości e-mail w czasie rejestracji użytkownika. Wiadomość została wysłana do administratora tej witryny."
```

2022-08-25 20:59 UTC, zwiastunsw commented on language/pl-PL/com_users.ini
> +COM_USERS_REGISTRATION_SAVE_SUCCESS="Dziękujemy za rejestrację. Możesz teraz zalogować się na stronie internetowej przy pomocy nazwy użytkownika i hasła użytych podczas rejestracji."
Komentarz w wierszu 116
```suggestion
COM_USERS_REGISTRATION_SAVE_SUCCESS="Dziękujemy za rejestrację. Możesz teraz zalogować się do witryny przy pomocy nazwy użytkownika i hasła użytych podczas rejestracji."
```

2022-08-25 20:59 UTC, zwiastunsw commented on language/pl-PL/com_users.ini
> +COM_USERS_REGISTRATION_COMPLETE_VERIFY="Twoje konto zostało utworzone i odnośnik aktywacyjny został wysłany na podany adres e-mail. Pamiętaj, że musisz aktywować konto, wybierając odnośnik aktywacyjn
Komentarz w wierszu 116
```suggestion
COM_USERS_REGISTRATION_COMPLETE_VERIFY="Twoje konto zostało utworzone i odnośnik aktywacyjny został wysłany na podany adres e-mail. Pamiętaj, że musisz aktywować konto, wybierając odnośnik aktywacyjny w otrzymanej wiadomości e-mail, którą dostaniesz. Aktywacja konta i weryfikacja przez administratora jest wymagane przed pierwszym zalogowaniem się do witryny."
```

2022-08-25 20:59 UTC, zwiastunsw commented on language/pl-PL/com_users.ini
> +COM_USERS_CAPTCHA_LABEL="Captcha"
Do zamiany we wszystkich plikach, gdzie występuje.

2022-08-25 20:59 UTC, zwiastunsw commented on language/pl-PL/com_users.ini
> +COM_USERS_EDIT_PROFILE="Edytuj profil"
Od 1.5 tłumaczymy "Edit" na "Dostosuj", "New" na "Utwórz". Tak jest we wszystkich nowszych polskich książkach. Dlatego opowiadam się za pozostawieniem, jak jest 
```suggestion
COM_USERS_EDIT_PROFILE="Dostosuj profil"
```

2022-08-25 20:59 UTC, zwiastunsw commented on language/pl-PL/com_users.ini
> +COM_USERS_EMAIL_ACTIVATED_BY_ADMIN_ACTIVATION_BODY="Witamy {NAME},\n\nTwoje konto zostało zatwierdzone przez administratora. Możesz zalogować się teraz na {SITEURL} używając nazwy użytkownika {USERNA
```suggestion
COM_USERS_EMAIL_ACTIVATED_BY_ADMIN_ACTIVATION_BODY="Witamy {NAME},\n\nTwoje konto zostało zatwierdzone przez administratora. Możesz zalogować się teraz na {SITEURL}, używając nazwy użytkownika {USERNAME} i hasła podanych podczas rejestracji."
```

2022-08-25 20:59 UTC, zwiastunsw commented on language/pl-PL/com_users.ini
> +COM_USERS_EMAIL_REGISTERED_NOTIFICATION_TO_ADMIN_BODY="Witaj administratorze, \n\nNowy użytkownik '{NAME}', nazwa użytkownika: '{USERNAME}', zarejestrował się na {SITEURL}."
To zwrot do adresata
```suggestion
COM_USERS_EMAIL_REGISTERED_NOTIFICATION_TO_ADMIN_BODY="Witaj Administratorze, \n\nNowy użytkownik '{NAME}', nazwa użytkownika: '{USERNAME}', zarejestrował się na {SITEURL}."
```

2022-08-25 20:59 UTC, zwiastunsw commented on language/pl-PL/com_users.ini
> +COM_USERS_FIELD_RESET_PASSWORD1_MESSAGE="Podane hasła nie są identyczne. Wprowadź żądane hasło w polu hasła oraz potwierdź je w polu powtórzenia hasła"
"Wprowadź" jest oczywiście poprawne, ale kiedyś ustalaliśmy, że będziemy używać krótszego "Wpisz". Więc raczej:  
```suggestion
COM_USERS_FIELD_RESET_PASSWORD1_MESSAGE="Podane hasła nie są identyczne. Wpisz żądane hasło w polu hasła oraz potwierdź je w polu powtórzenia hasła"
```

2022-08-25 20:59 UTC, zwiastunsw commented on language/pl-PL/com_users.ini
> +COM_USERS_LOGIN_REMIND="Nie pamiętasz nazwy użytkownika?"
W kontekście jest zrozumiałe, o co chodzi. W module, zwłaszcza na urządzeniach mobilnych, etykieta łącza trochę przydługa. Pozostawiłbym bez zmian (ewentualnie dodać krótsze "swojej nazwy"). 
```suggestion
COM_USERS_LOGIN_REMIND="Nie pamiętasz nazwy?"
```

2022-08-25 20:59 UTC, zwiastunsw commented on language/pl-PL/com_users.ini
> +COM_USERS_PROFILE_DEFAULT_LABEL="Edytuj swój profil"
"Twoje dane" jest prostsze, 'profil" jest słowem spoza podstawowego słownika. Zostawmy, jak było.  Zwłaszcza, że służy także do przeglądania, niekoniecznie edycji danych. 
```suggestion
COM_USERS_PROFILE_DEFAULT_LABEL="Twoje dane"
```

2022-08-25 20:59 UTC, zwiastunsw commented on language/pl-PL/com_users.ini
> +COM_USERS_PROFILE_NOCHANGE_USERNAME_DESC="Jeśli chcesz zmienić swoją nazwę użytkownika, skontaktuj się z administratorem strony internetowej"
```suggestion
COM_USERS_PROFILE_NOCHANGE_USERNAME_DESC="Jeśli chcesz zmienić swoją nazwę użytkownika, skontaktuj się z administratorem witryny."
```

2022-08-25 20:59 UTC, zwiastunsw commented on language/pl-PL/com_users.ini
> +COM_USERS_PROFILE_PASSWORD1_MESSAGE="Podane hasła nie są identyczne. Wprowadź żądane hasło w polu hasła oraz potwierdź je w polu powtórzenia hasła."
```suggestion
COM_USERS_PROFILE_PASSWORD1_MESSAGE="Podane hasła nie są identyczne. Wpisz żądane hasło w polu hasła oraz potwierdź je w polu powtórzenia hasła."
```

2022-08-25 20:59 UTC, zwiastunsw commented on language/pl-PL/com_users.ini
> +COM_USERS_REGISTRATION_COMPLETE_ACTIVATE="Twoje konto zostało utworzone i odnośnik aktywacyjny został wysłany na podany adres e-mail. Pamiętaj, że musisz aktywować konto, wybierając odnośnik aktywacy
```suggestion
COM_USERS_REGISTRATION_COMPLETE_ACTIVATE="Twoje konto zostało utworzone i odnośnik aktywacyjny został wysłany na podany adres e-mail. Pamiętaj, że musisz aktywować konto, wybierając odnośnik aktywacyjny w otrzymanej wiadomości e-mail, którą dostaniesz. Aktywacja konta jest wymagana przed pierwszym zalogowaniem się do witryny."
```

2022-08-25 20:59 UTC, zwiastunsw commented on language/pl-PL/com_users.ini
> +COM_USERS_REMIND_LIMIT_ERROR_N_HOURS="Przekroczono maksymalną dozwoloną liczbę resetowań hasła. Spróbuj ponownie za %s godzin."
Liczebniki w języku polskim przybierając  w tym kontekście jedną z trzech form. Poprawki należy wprowadzać zgodnie ze wzorcem wszędzie tam, gdzie z jakiegoś powodu zostało dawne rozwiązane (tylko dwie formy). Wzorzec jest w pliku localise.php - https://github.com/JoomlaPolska/jezyk-J4/blob/a6831fa347da3586cc158887f803fb79ef4225a4/administrator/language/pl-PL/localise.php#L28-L46.

2022-08-25 20:59 UTC, zwiastunsw commented on language/pl-PL/com_users.ini
> +COM_USERS_REMIND_LIMIT_ERROR_N_HOURS_1="Przekroczono maksymalną dozwoloną liczbę resetowań hasła. Spróbuj ponownie za godzinę."
Uwaga jak do wiersza 120

2022-08-28 13:32 UTC, Valdnet commented
@zwiastunsw Dzięki za wskazówki dotyczące tłumaczenia w Joomli, na których bazują się tłumacze.
Wszystkie sugestie zostały wprowadzone oraz dodane niewielkie poprawki tłumaczenia.

Teraz można zauważyć, że nowy tłumacz jeśli nawet chce i ma chęci przetłumaczyć nowe ciągi tekstowe ma utrudnione zadanie, choćby z powodu przyjętego nazewnictwa, czy zmiany nazw ciągów tekstowych z powodu odmiany przez liczbę pojedynczą i mnogą.

Jeśli projekt tłumaczenia byłby tłumaczony na portalu tłumaczeń do tego specjalnie stworzonym, mógłby porównywać tłumaczenia z innymi, korzystać ze sugestii nazewnictwa, a ciągi tekstowe które odmieniają się przez liczbę pojedynczą i mnogą miałyby gotowe to tego stworzone ciągi, a tłumacz nie musiałby się nad tym zastanawiać, tylko mógłby bardziej skupiać się na poprawnym tłumaczeniu.

2022-08-28 20:30 UTC, zwiastunsw approved these changes

2022-08-28 20:31 UTC, zwiastunsw approved these changes

2022-08-28 21:07 UTC, merged